### ISSUE TITLE
KML files

### ISSUE THREAD

**Issue by dvh** [geo4web-testbed/topic3#45]
Google supports KML files to understand geodata. The KML file(s) can be crawled by providing a link to the file(s) in the XML Sitemap. See also: https://developers.google.com/kml/documentation/

**Comment by pvgenuchten** [comment]
Nice, @dvh does the kml allow to have objects at locations annotated as schema.org, or it just has links at a location that links to geojson/rdfa which then has the schema.org annotation?

**Comment by dvh** [comment]
@pvgenuchten it appears to have it's own annotations (see below), but we're definitely going to try it out. Bing supports it as well by the way.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Folder>
    <name>Ground Overlays</name>
    <description>Examples of ground overlays</description>
    <GroundOverlay>
      <name>Large-scale overlay on terrain</name>
      <description>Overlay shows Mount Etna erupting 
          on July 13th, 2001.</description>
      <Icon>
        <href>http://developers.google.com/kml/documentation/images/etna.jpg</href>
      </Icon>
      <LatLonBox>
        <north>37.91904192681665</north>
        <south>37.46543388598137</south>
        <east>15.35832653742206</east>
        <west>14.60128369746704</west>
        <rotation>-0.1556640799496235</rotation>
      </LatLonBox>
    </GroundOverlay>
  </Folder>
</kml>
```

**Comment by dvh** [comment]
I wonder if it still is getting crawled by the way: https://developers.google.com/maps/support/kmlmaps

**Comment by dvh** [comment]
application/vnd.google-earth.kml+xml representation is fixed, still need to summon this response on *.kml request.
